version: '3.0'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - "9000"

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/bvan-pae/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/bvan-pae/data/wordpress
      o: bind
